FROM mcr.microsoft.com/dotnet/sdk:6.0
ENV DOTNET_ENVIRONMENT=Development
EXPOSE 80

WORKDIR /src

COPY ["Services/CommentsFetchStatusIntegration/CommentsFetchStatusIntegration.Worker/CommentsFetchStatusIntegration.Worker.csproj", "Services/CommentsFetchStatusIntegration/CommentsFetchStatusIntegration.Worker/"]

RUN dotnet restore Services/CommentsFetchStatusIntegration/CommentsFetchStatusIntegration.Worker/CommentsFetchStatusIntegration.Worker.csproj

COPY . .
WORKDIR "/src/Services/CommentsFetchStatusIntegration/CommentsFetchStatusIntegration.Worker"
RUN dotnet build -c Debug

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "Debug", "--"]