FROM mcr.microsoft.com/dotnet/sdk:6.0
ENV DOTNET_ENVIRONMENT=Development
EXPOSE 80

WORKDIR /src

COPY ["Services/CommentsFetchStatusManager/CommentsFetchStatusManager.MinimalApi/CommentsFetchStatusManager.MinimalApi.csproj", "Services/CommentsFetchStatusManager/CommentsFetchStatusManager.MinimalApi/"]

RUN dotnet restore Services/CommentsFetchStatusManager/CommentsFetchStatusManager.MinimalApi/CommentsFetchStatusManager.MinimalApi.csproj

COPY . .
WORKDIR "/src/Services/CommentsFetchStatusManager/CommentsFetchStatusManager.MinimalApi"
RUN dotnet build -c Debug

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "Debug", "--"]