FROM mcr.microsoft.com/dotnet/sdk:6.0
ENV ASPNETCORE_ENVIRONMENT=Development
EXPOSE 80

WORKDIR /src

COPY ["Services/VideoExecutionStatus/VideoExecutionStatus.MinimalApi/VideoExecutionStatus.MinimalApi.csproj", "Services/VideoExecutionStatus/VideoExecutionStatus.MinimalApi/"]

RUN dotnet restore Services/VideoExecutionStatus/VideoExecutionStatus.MinimalApi/VideoExecutionStatus.MinimalApi.csproj

COPY . .
WORKDIR "/src/Services/VideoExecutionStatus/VideoExecutionStatus.MinimalApi"
RUN dotnet build -c Debug

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "Debug", "--"]