version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data

  hadzy-gateway.api.dev:
    image: hadzy/gateway.api:1.0.0
    ports:
      - "5111:5111"
    build:
      context: .
      dockerfile: ApiGateway/GateWay.Api/Dockerfile.develop
    environment:
      - ASPNETCORE_URLS=http://*:5111

  hadzy-comments.storage.worker.dev:
    image: hadzy/comments.storage.worker:1.0.0
    ports:
      - "5121:5121"
    build:
      context: .
      dockerfile: Services/CommentsStorage/CommentsStorage.Worker/Dockerfile.develop
    environment:
      - ASPNETCORE_URLS=http://*:5121

  hadzy-video.comments.api.dev:
    image: hadzy/video.comments.api:1.0.0
    ports:
      - "5131:5131"
    build:
      context: .
      dockerfile: Services/VideoComments/VideoComments.MinimalApi/Dockerfile.develop
    environment:
      - ASPNETCORE_URLS=http://*:5131

  hadzy-video.execution.status.api.dev:
    image: hadzy/video.execution.status.api:1.0.0
    ports:
      - "5141:5141"
    build:
      context: .
      dockerfile: Services/VideoExecutionStatus/VideoExecutionStatus.MinimalApi/Dockerfile.develop
    environment:
      - ASPNETCORE_URLS=http://*:5141

  hadzy-comments.fetcher.worker.dev:
    image: hadzy/comments.fetcher.api:1.0.0
    ports:
      - "5151:5151"
    build:
      context: .
      dockerfile: Services/YouTubeCommentsFetcher/YouTubeCommentsFetcher.Worker/Dockerfile.develop
    environment:
      - ASPNETCORE_URLS=http://*:5151

  hadzy-video.fetcher.api.dev:
    image: hadzy/video.fetcher.api:1.0.0
    ports:
      - "5161:5161"
    build:
      context: .
      dockerfile: Services/YouTubeVideoFetcher/YouTubeVideoFetcher.MinimalApi/Dockerfile.develop
    environment:
      - ASPNETCORE_URLS=http://*:5161
      - YouTube:ApiKey=${YOUTUBE_APIKEY}
      - Seq:Url=${SEQ_URL}

volumes:
  seq-data: