version: '3.4'

services:
    
  hadzy-comments.fetcher.worker.dev:
    image: hadzy/comments.fetcher.worker:1.0.0
    ports:
      - "5151:5151"
    build:
      context: .
      dockerfile: Services/YouTubeCommentsFetcher/YouTubeCommentsFetcher.Worker/Dockerfile.develop
    environment:
      - ASPNETCORE_URLS=http://*:5151
      - YouTube:ApiKey=${YOUTUBE_APIKEY}
      - Seq:Url=${SEQ_URL}
      - RabbitMq:Hostname=${RABBITMQ_HOSTNAME}
      - RabbitMq:User=${RABBITMQ_USER}
      - RabbitMq:Password=${RABBITMQ_PASSWORD}
        
  hadzy-comments.fetch.status.integration.worker.dev:
    image: hadzy/comments.fetch.status.integration.worker:1.0.0
    ports:
      - "5171:5171"
    build:
      context: .
      dockerfile: Services/CommentsFetchStatusIntegration/CommentsFetchStatusIntegration.Worker/Dockerfile.develop
    environment:
      - ASPNETCORE_URLS=http://*:5171
      - Seq:Url=${SEQ_URL}
      - RabbitMq:Hostname=${RABBITMQ_HOSTNAME}
      - RabbitMq:User=${RABBITMQ_USER}
      - RabbitMq:Password=${RABBITMQ_PASSWORD}
      - MongoDb:ConnectionString=${MONGODB_CONNECTIONSTRING}
      - MongoDb:DatabaseName=${MONGODB_DATABASENAME}
      - MongoDb:VideoFetchInfoCollectionName=${MONGODB_VIDEOFETCHINFOCOLLECTIONNAME}
  
  hadzy-comments.fetch.status.manager.api.dev:
    image: hadzy/comments.fetch.status.manager.api:1.0.0
    ports:
      - "5181:5181"
    build:
      context: .
      dockerfile: Services/CommentsFetchStatusManager/CommentsFetchStatusManager.MinimalApi/Dockerfile.develop
    environment:
      - ASPNETCORE_URLS=http://*:5181
      - Seq:Url=${SEQ_URL}
      - RabbitMq:Hostname=${RABBITMQ_HOSTNAME}
      - RabbitMq:User=${RABBITMQ_USER}
      - RabbitMq:Password=${RABBITMQ_PASSWORD}
      - MongoDb:ConnectionString=${MONGODB_CONNECTIONSTRING}
      - MongoDb:DatabaseName=${MONGODB_DATABASENAME}
      - MongoDb:VideoFetchInfoCollectionName=${MONGODB_VIDEOFETCHINFOCOLLECTIONNAME}