version: '3.4'

services:
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  
  hadzy-gateway.api.prod:
    image: hadzy/gateway.api:1.0.0
    ports:
      - "8080:5000"
    build:
      context: .
      dockerfile: ApiGateway/GateWay.Api/Dockerfile.develop
    environment:
      - ASPNETCORE_URLS=http://+:5000