version: '3.4'

services:

  hadzy-comments.fetch.status.integration.worker.dev:
    image: hadzy/comments.fetch.status.integration.worker:1.0.0
    ports:
      - "5171:5171"
    build:
      context: .
      dockerfile: Services/CommentsFetchStatusIntegration/CommentsFetchStatusIntegration.Worker/Dockerfile.develop
    environment:
      - ASPNETCORE_URLS=http://*:5171
      - Seq:Url=${SEQ_URL}
      - RabbitMq:Hostname=${RABBITMQ_HOSTNAME}
      - RabbitMq:User=${RABBITMQ_USER}
      - RabbitMq:Password=${RABBITMQ_PASSWORD}